// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfjgrkfxzvoczvsuvoqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmamdya2Z4enZvY3p2c3V2b3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzI2ODUsImV4cCI6MjA2MDkwODY4NX0.pw8BHOPQ0c8GSyGu7o1T5NhLyLqmb86qoY2beo7Hyjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);